name: vtfa continuous integration

on:
  pull_request:
    branches: ['main', 'dev']

jobs:
  build:
    name: vtfa build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build